name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Ajouté pour pouvoir lancer le workflow manuellement

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run tests
        run: npm test -- --json --outputFile=test-results.json

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.json

      - name: Generate test results for README
        run: |
          echo "## Résultats des Tests Unitaires" > test-results.md
          echo "" >> test-results.md
          echo '```' >> test-results.md
          cat test-results.json | jq '.testResults[] | "\(.name): \(.status)"' >> test-results.md
          echo '```' >> test-results.md

      - name: Update README with test results
        run: |
          sed -i '/## Résultats des Tests Unitaires/,$d' README.md
          cat test-results.md >> README.md
          rm test-results.md

      - name: Commit test results
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet && echo "Pas de modifications à committer" || (git add README.md && git commit -m "Mise à jour des résultats des tests dans le README" && git push)